# Generated by Django 5.0.3 on 2024-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='on_main',
        ),
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='user',
            name='flag_legal_entity',
            field=models.CharField(choices=[('P', 'Физичское лицо'), ('L', 'Юридическое лицо')], default='Юридическое лицо', max_length=1, verbose_name='Лицо'),
        ),
        migrations.AddField(
            model_name='user',
            name='ogrn',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True, verbose_name='ОГРН'),
        ),
    ]
