# Generated by Django 5.0.3 on 2024-04-11 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_on_main_user_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 11, 14, 11, 6, 304674, tzinfo=datetime.timezone.utc), verbose_name='Дата авторизации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='flag_legal_entity',
            field=models.CharField(choices=[('P', 'Физическое лицо'), ('L', 'Юридическое лицо')], default='Юридическое лицо', max_length=1, verbose_name='Лицо'),
        ),
    ]
