# Generated by Django 5.0.3 on 2024-04-12 09:30

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'IP адресс',
                'verbose_name_plural': 'IP адреса',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звезды рейтинга',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Сurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_currency', models.CharField(help_text='Укажите название валюты', max_length=200, verbose_name='Название валюты')),
                ('char_currency', models.CharField(help_text='Укажите значок валюты символом', max_length=10, verbose_name='Символ валюты')),
                ('currency_image', models.ImageField(blank=True, help_text='Указжите картинку валюты', null=True, upload_to='currency_image/', verbose_name='Картинка валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Укажите название латиницей', verbose_name='Название категории')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название продукта', max_length=200, verbose_name='Заглавие')),
                ('slug', models.SlugField(help_text='Укажите название латиницей', unique=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Укажите описание группы', verbose_name='Название')),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='Укажите стоимость продукта', max_digits=30, null=True, verbose_name='Стоимость')),
                ('address', models.CharField(help_text='Укажите адрес, где находиться продукт', max_length=200, verbose_name='Адрес')),
                ('published', models.BooleanField(default=False, help_text='Опубликован продукт или нет', verbose_name='Флаг публикации')),
                ('moderation', models.BooleanField(default=False, help_text='Публикуем ли объявление или нет', verbose_name='Флаг публикации(модерации)')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date_now', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Автор поста', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='products.category', verbose_name='Категория')),
                ('number_of_views', models.ManyToManyField(blank=True, help_text='IP адрес, который просмотрел карточку товара', related_name='card_views', to='products.ip')),
                ('currency', models.ForeignKey(blank=True, help_text='Валюта продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency', to='products.сurrency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст комментария', max_length=1024, verbose_name='Текст комментария')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date_now', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Автор комментария', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('card', models.ForeignKey(help_text='Комментарий продукта', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.card', verbose_name='Комментарий продукта')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('card', models.ForeignKey(help_text='Продукт', on_delete=django.db.models.deletion.CASCADE, to='products.card', verbose_name='Продукт')),
                ('star', models.ForeignKey(help_text='Звезда рейтинга', on_delete=django.db.models.deletion.CASCADE, to='products.ratingstar', verbose_name='Звезда рейтинга')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
    ]
