# Generated by Django 5.0.3 on 2024-04-12 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='meta',
            field=models.CharField(default=datetime.datetime(2024, 4, 12, 13, 13, 46, 222271), help_text='Мета JSON', max_length=1024, verbose_name='Мета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 12, 13, 14, 1, 10306), verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='pub_date_now',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='ip',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 12, 10, 15, 58, 853324, tzinfo=datetime.timezone.utc), verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ip',
            name='pub_date_now',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='rating',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 12, 10, 16, 31, 293138, tzinfo=datetime.timezone.utc), verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='pub_date_now',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='ratingstar',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 12, 10, 16, 34, 930391, tzinfo=datetime.timezone.utc), verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratingstar',
            name='pub_date_now',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='сurrency',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 12, 10, 17, 19, 319275, tzinfo=datetime.timezone.utc), verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='сurrency',
            name='pub_date_now',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='card',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='card',
            name='pub_date_now',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date_now',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
