# Generated by Django 5.0.3 on 2024-04-12 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_card_meta_category_pub_date_category_pub_date_now_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='author',
            field=models.ForeignKey(help_text='Автор поста', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='card',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Валюта продукта', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency', to='products.сurrency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number_of_views',
            field=models.ManyToManyField(blank=True, help_text='IP адрес, который просмотрел карточку товара', related_name='card_views', to='products.ip', verbose_name='Просмотр'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Автор комментария', on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='card',
            field=models.ForeignKey(help_text='Комментарий продукта', on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='products.card', verbose_name='Комментарий продукта'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='card',
            field=models.ForeignKey(help_text='Продукт', on_delete=django.db.models.deletion.PROTECT, to='products.card', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(help_text='Звезда рейтинга', on_delete=django.db.models.deletion.PROTECT, to='products.ratingstar', verbose_name='Звезда рейтинга'),
        ),
    ]
